In [22]:
import pandas as pd
import datetime
import sqlite3

First we need to connect to a database. Only after the connection is established, we can query the DB.

We cannot use to URL, but we need to download the [DB](https://github.com/gdv/foundationsCS/raw/master/students/ex-data/Northwind/Northwind_large.sqlite) and save it on the disk.

In [23]:
cnx = sqlite3.connect('../students/ex-data/Northwind/Northwind_large.sqlite')
c = cnx.cursor()

In [24]:
c.execute('SELECT * FROM employees')
results = c.fetchall()
results

[(1,
  'Davolio',
  'Nancy',
  'Sales Representative',
  'Ms.',
  '1980-12-08',
  '2024-05-01',
  '507 - 20th Ave. E. Apt. 2A',
  'Seattle',
  'North America',
  '98122',
  'USA',
  '(206) 555-9857',
  '5467',
  None,
  "Education includes a BA in psychology from Colorado State University in 1970.  She also completed 'The Art of the Cold Call.'  Nancy is a member of Toastmasters International.",
  2,
  'http://accweb/emmployees/davolio.bmp'),
 (2,
  'Fuller',
  'Andrew',
  'Vice President, Sales',
  'Dr.',
  '1984-02-19',
  '2024-08-14',
  '908 W. Capital Way',
  'Tacoma',
  'North America',
  '98401',
  'USA',
  '(206) 555-9482',
  '3457',
  None,
  'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.',
  None,
  'http://accweb/emmployees/fuller.bmp'),
 (3,
  'Leverling',
  'Janet',
  'Sales Representative',
  'Ms.',
  '1995-08-30',
  '2024-04-01',
  '722 Moss Bay Blvd.',
  'Kirkland',
  'North America',
  '98033',
  'USA',
  '(206) 555-3412',
  '3355',
  None,
  'Janet has a BS degree in chemistry from Boston College (1984).  She has also completed a certificate program in food retailing management.  Janet was hired as a sales associate in 1991 and promoted to sales representative in February 1992.',
  2,
  'http://accweb/emmployees/leverling.bmp'),
 (4,
  'Peacock',
  'Margaret',
  'Sales Representative',
  'Mrs.',
  '1969-09-19',
  '2025-05-03',
  '4110 Old Redmond Rd.',
  'Redmond',
  'North America',
  '98052',
  'USA',
  '(206) 555-8122',
  '5176',
  None,
  'Margaret holds a BA in English literature from Concordia College (1958) and an MA from the American Institute of Culinary Arts (1966).  She was assigned to the London office temporarily from July through November 1992.',
  2,
  'http://accweb/emmployees/peacock.bmp'),
 (5,
  'Buchanan',
  'Steven',
  'Sales Manager',
  'Mr.',
  '1987-03-04',
  '2025-10-17',
  '14 Garrett Hill',
  'London',
  'British Isles',
  'SW1 8JR',
  'UK',
  '(71) 555-4848',
  '3453',
  None,
  "Steven Buchanan graduated from St. Andrews University, Scotland, with a BSC degree in 1976.  Upon joining the company as a sales representative in 1992, he spent 6 months in an orientation program at the Seattle office and then returned to his permanent post in London.  He was promoted to sales manager in March 1993.  Mr. Buchanan has completed the courses 'Successful Telemarketing' and 'International Sales Management.'  He is fluent in French.",
  2,
  'http://accweb/emmployees/buchanan.bmp'),
 (6,
  'Suyama',
  'Michael',
  'Sales Representative',
  'Mr.',
  '1995-07-02',
  '2025-10-17',
  'Coventry House Miner Rd.',
  'London',
  'British Isles',
  'EC2 7JR',
  'UK',
  '(71) 555-7773',
  '428',
  None,
  "Michael is a graduate of Sussex University (MA, economics, 1983) and the University of California at Los Angeles (MBA, marketing, 1986).  He has also taken the courses 'Multi-Cultural Selling' and 'Time Management for the Sales Professional.'  He is fluent in Japanese and can read and write French, Portuguese, and Spanish.",
  5,
  'http://accweb/emmployees/davolio.bmp'),
 (7,
  'King',
  'Robert',
  'Sales Representative',
  'Mr.',
  '1992-05-29',
  '2026-01-02',
  'Edgeham Hollow Winchester Way',
  'London',
  'British Isles',
  'RG1 9SP',
  'UK',
  '(71) 555-5598',
  '465',
  None,
  "Robert King served in the Peace Corps and traveled extensively before completing his degree in English at the University of Michigan in 1992, the year he joined the company.  After completing a course entitled 'Selling in Europe,' he was transferred to the London office in March 1993.",
  5,
  'http://accweb/emmployees/davolio.bmp'),
 (8,
  'Callahan',
  'Laura',
  'Inside Sales Coordinator',
  'Ms.',
  '1990-01-09',
  '2026-03-05',
  '4726 - 11th Ave. N.E.',
  'Seattle',
  'North America',
  '98105',
  'USA',
  '(206) 555-1189',
  '2344',
  None,
  'Laura received a BA in psychology from the University of Washington.  She has also completed a course in business French.  She reads and writes French.',
  2,
  'http://accweb/emmployees/davolio.bmp'),
 (9,
  'Dodsworth',
  'Anne',
  'Sales Representative',
  'Ms.',
  '1998-01-27',
  '2026-11-15',
  '7 Houndstooth Rd.',
  'London',
  'British Isles',
  'WG2 7LT',
  'UK',
  '(71) 555-4444',
  '452',
  None,
  'Anne has a BA degree in English from St. Lawrence College.  She is fluent in French and German.',
  5,
  'http://accweb/emmployees/davolio.bmp'),
 (10,
  'Rossi',
  'Maria',
  'Sales Representative',
  '',
  '1995-08-30',
  '2020-01-01',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None)]

In [25]:
employees = pd.DataFrame(results)
employees.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1,Davolio,Nancy,Sales Representative,Ms.,1980-12-08,2024-05-01,507 - 20th Ave. E. Apt. 2A,Seattle,North America,98122,USA,(206) 555-9857,5467,None,Education includes a BA in psychology from Col...,2.0,http://accweb/emmployees/davolio.bmp
1,2,Fuller,Andrew,"Vice President, Sales",Dr.,1984-02-19,2024-08-14,908 W. Capital Way,Tacoma,North America,98401,USA,(206) 555-9482,3457,None,Andrew received his BTS commercial in 1974 and...,NaN,http://accweb/emmployees/fuller.bmp
2,3,Leverling,Janet,Sales Representative,Ms.,1995-08-30,2024-04-01,722 Moss Bay Blvd.,Kirkland,North America,98033,USA,(206) 555-3412,3355,None,Janet has a BS degree in chemistry from Boston...,2.0,http://accweb/emmployees/leverling.bmp
3,4,Peacock,Margaret,Sales Representative,Mrs.,1969-09-19,2025-05-03,4110 Old Redmond Rd.,Redmond,North America,98052,USA,(206) 555-8122,5176,None,Margaret holds a BA in English literature from...,2.0,http://accweb/emmployees/peacock.bmp
4,5,Buchanan,Steven,Sales Manager,Mr.,1987-03-04,2025-10-17,14 Garrett Hill,London,British Isles,SW1 8JR,UK,(71) 555-4848,3453,None,Steven Buchanan graduated from St. Andrews Uni...,2.0,http://accweb/emmployees/buchanan.bmp

In [26]:
employees = pd.read_sql_query('SELECT * FROM employees', cnx)
employees.head()

,Id,LastName,FirstName,Title,TitleOfCourtesy,BirthDate,HireDate,Address,City,Region,PostalCode,Country,HomePhone,Extension,Photo,Notes,ReportsTo,PhotoPath
0,1,Davolio,Nancy,Sales Representative,Ms.,1980-12-08,2024-05-01,507 - 20th Ave. E. Apt. 2A,Seattle,North America,98122,USA,(206) 555-9857,5467,None,Education includes a BA in psychology from Col...,2.0,http://accweb/emmployees/davolio.bmp
1,2,Fuller,Andrew,"Vice President, Sales",Dr.,1984-02-19,2024-08-14,908 W. Capital Way,Tacoma,North America,98401,USA,(206) 555-9482,3457,None,Andrew received his BTS commercial in 1974 and...,NaN,http://accweb/emmployees/fuller.bmp
2,3,Leverling,Janet,Sales Representative,Ms.,1995-08-30,2024-04-01,722 Moss Bay Blvd.,Kirkland,North America,98033,USA,(206) 555-3412,3355,None,Janet has a BS degree in chemistry from Boston...,2.0,http://accweb/emmployees/leverling.bmp
3,4,Peacock,Margaret,Sales Representative,Mrs.,1969-09-19,2025-05-03,4110 Old Redmond Rd.,Redmond,North America,98052,USA,(206) 555-8122,5176,None,Margaret holds a BA in English literature from...,2.0,http://accweb/emmployees/peacock.bmp
4,5,Buchanan,Steven,Sales Manager,Mr.,1987-03-04,2025-10-17,14 Garrett Hill,London,British Isles,SW1 8JR,UK,(71) 555-4848,3453,None,Steven Buchanan graduated from St. Andrews Uni...,2.0,http://accweb/emmployees/buchanan.bmp

In [27]:
employees = pd.read_sql_table('Employees', 'sqlite:///../students/ex-data/Northwind/Northwind_large.sqlite')
employees.head()

,Id,LastName,FirstName,Title,TitleOfCourtesy,BirthDate,HireDate,Address,City,Region,PostalCode,Country,HomePhone,Extension,Photo,Notes,ReportsTo,PhotoPath
0,1,Davolio,Nancy,Sales Representative,Ms.,1980-12-08,2024-05-01,507 - 20th Ave. E. Apt. 2A,Seattle,North America,98122,USA,(206) 555-9857,5467,None,Education includes a BA in psychology from Col...,2.0,http://accweb/emmployees/davolio.bmp
1,2,Fuller,Andrew,"Vice President, Sales",Dr.,1984-02-19,2024-08-14,908 W. Capital Way,Tacoma,North America,98401,USA,(206) 555-9482,3457,None,Andrew received his BTS commercial in 1974 and...,NaN,http://accweb/emmployees/fuller.bmp
2,3,Leverling,Janet,Sales Representative,Ms.,1995-08-30,2024-04-01,722 Moss Bay Blvd.,Kirkland,North America,98033,USA,(206) 555-3412,3355,None,Janet has a BS degree in chemistry from Boston...,2.0,http://accweb/emmployees/leverling.bmp
3,4,Peacock,Margaret,Sales Representative,Mrs.,1969-09-19,2025-05-03,4110 Old Redmond Rd.,Redmond,North America,98052,USA,(206) 555-8122,5176,None,Margaret holds a BA in English literature from...,2.0,http://accweb/emmployees/peacock.bmp
4,5,Buchanan,Steven,Sales Manager,Mr.,1987-03-04,2025-10-17,14 Garrett Hill,London,British Isles,SW1 8JR,UK,(71) 555-4848,3453,None,Steven Buchanan graduated from St. Andrews Uni...,2.0,http://accweb/emmployees/buchanan.bmp

### Read all other DB tables

Another possibility is to exploit the fact that the `sqlite_master` table contains the catalog of all tables in the DB.

## Compute the number of employees hired in each year

## Find the manager (that is, employee that do not report to any other person), who have been hired the most time.

## Find the orders with the longest time between the submission and the approval.

## Find the order that has the most items

## Compute how the current number of units in stock is distributed among all categories

## Find the categories with the largest number of items in stock.